# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 13:34
from __future__ import unicode_literals

import ckw_appointments.utils.upload_handlers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('begin_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('read_groups', models.ManyToManyField(to='auth.Group')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('urgency', models.IntegerField(choices=[(0, b'low'), (50, b'mid'), (100, b'high')])),
                ('time_planned', models.FloatField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ckw_appointments.Appointment')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ckw_appointments.AppointmentTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filefield', models.FileField(upload_to=ckw_appointments.utils.upload_handlers.taskupload_handler)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ckw_appointments.Appointment')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ckw_appointments.AppointmentTask')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_status_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'started', b'started'), (b'not_required', b'not required'), (b'not_possible', b'not possible'), (b'finished', b'finished')], max_length=100)),
                ('log_status_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ckw_appointments.AppointmentTask')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ckw_appointments.AppointmentApp'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
