# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckw_appointments', '0002_appointmentapp_overview_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='appointmentapp',
            options={'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='appointmenttask',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='appointmentupload',
            options={'verbose_name': 'Upload', 'verbose_name_plural': 'Uploads'},
        ),
        migrations.AlterModelOptions(
            name='tasklog',
            options={'verbose_name': 'Task Log', 'verbose_name_plural': 'Task Logs'},
        ),
    ]
