# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 13:59
from __future__ import unicode_literals

import ckw_appointments.utils.upload_handlers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckw_appointments', '0003_auto_20180320_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentupload',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmentupload',
            name='task',
        ),
        migrations.RemoveField(
            model_name='appointmentupload',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='appointmenttask',
            name='filefield',
            field=models.FileField(blank=True, null=True, upload_to=ckw_appointments.utils.upload_handlers.taskupload_handler),
        ),
        migrations.DeleteModel(
            name='AppointmentUpload',
        ),
    ]
